import React from 'react'

function privacy() {
  return (
<>
<div className='w-full h-screen bg-zinc-200'>
    <p>
    Privacy Policy:

At our darts scoreboard app, we take your privacy seriously and are committed to protecting your personal information. This privacy policy explains what personal information we collect, how we use that information, and the steps we take to ensure the security and confidentiality of that information.

What Information We Collect:
When you create an account on our darts scoreboard app, we collect your name and email address. You also have the option to provide a phone number. If you sign in with Google, Facebook, or OAuth, we may collect information from your social media or third-party account, such as your name, email address, and profile picture. Additionally, we use Google Analytics to track geographic location, which collects data about your device, browser, and IP address.

How We Use Your Information:
We use your personal information to create and maintain your account, and to provide you with access to our darts scoreboard app. We may also use your information to send you promotional emails or other marketing materials, but only if you have opted in to receive them. We do not sell or share your personal information with third parties for marketing purposes.

Security and Confidentiality:
We take appropriate measures to ensure the security and confidentiality of your personal information. This includes using industry-standard encryption to protect your data during transmission, and limiting access to your data to authorized personnel only. However, please note that no system can guarantee 100% security, and we cannot be responsible for any unauthorized access or disclosure of your personal information.

Google Analytics:
Our darts scoreboard app uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help us analyze how users interact with our app. The information generated by the cookie about your use of the app (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the app, compiling reports on app activity for app operators and providing other services relating to app activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. By using our app, you consent to the processing of data about you by Google in the manner and for the purposes set out above.

Terms of Service:

By using our darts scoreboard app, you agree to the following terms of service:

You must be 18 years of age or older to use our app.
You agree to provide accurate and complete information when creating your account.
You are responsible for maintaining the confidentiality of your account login information, and for all activities that occur under your account.
You agree to use our app for lawful purposes only, and not to engage in any activity that violates applicable laws or regulations.
We reserve the right to terminate your account or restrict your access to our app at any time, for any reason, without notice or liability.
Our app is provided on an "as is" basis, and we make no warranties or representations about the quality, accuracy, or reliability of the information or services provided.
We are not responsible for any loss or damage that may result from your use of our app, or from any interruption or downtime of our app.
We reserve the right to modify or update these terms of service at any time, without notice or liability. It is your responsibility to review these terms of service periodically to ensure that you are aware of any changes.
    </p>
    
</div>
</>
  )
}

export default privacy
